language: python
python:
  - "2.7"
  - "3.5"
sudo: false
notifications:
  email: false
install:
  - pip install --upgrade pip wheel
  - pip install --upgrade numpy
  - pip install sphinx
  - pip install .
script:
  - nosetests
  - cd docs && make html